sudo: required
language: python
os: linux
dist: bionic
env:
  matrix:
    - TRAVIS_EXTRA_JOB_WORKAROUND=true
matrix:
  include:
    - python: "3.7"
      env: VERSION_ARCH='9.5.1/tor-browser-linux64-9.5.1_en-US.tar.xz'
  exclude:
    - env: TRAVIS_EXTRA_JOB_WORKAROUND=true
before_install:
  - "export DISPLAY=:99.0"
install:
  - pip install pytest-cov pytest
  - pip install -r requirements.txt
  - sudo apt-get -qq install tcpdump libpcap-dev tshark xvfb
  - sh -e /etc/init.d/xvfb start
  - tarball=`echo $VERSION_ARCH | cut -d'/' -f 2`
  - wget https://archive.torproject.org/tor-package-archive/torbrowser/$VERSION_ARCH
  - tar -xf $tarball
  - export TBB_PATH=`pwd`/tor-browser_en-US
before_script:
  - cd tbcrawler/test
script: travis_retry py.test -s --cov=tbcrawler --cov-report term-missing --durations=10
